#! /bin/sh

localPath=$(dirname $(realpath $0))
cd $localPath

pnpm b
rsync -az -e ssh ./dist/ geoochi-sc:/home/ubuntu/projects/space/
tcb hosting deploy dist/ space/ -e singfor-live-9gizzbuc59a85fe6
